--- 
title: "A Hindu Search For A Nation"
author: "Vikram Upparpalli"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: VikramWritings/search_for_a_nation
description: "Making and Unmaking of a Nation"
---


<!--chapter:end:index.Rmd-->

# Prologue {#intro}

**_A Nation is an imagined political community - and imagined as both inherently limited and sovereign. All communities larger than primordial villages of face-to-face contact (and perhaps even these) are imagined. Communities are to be distinguished, not by their falsity/genuineness, but by the style in which they are imagined._** - Benedict Anderson, an Anglo-Irish political scientist and historian .

On March 11th, 1882,Ernest Renan's lecture, Qu’est-ce qu’une nation? - "What is a Nation?" confounds the idea of a race (linguistic and habitual) to that of a nation. It can't be farther than truth.

Britain vacated india much sooner than many expected it. The protests for dominion status held in india was not really making any impact. India's ask for freedom was not making any political impact to conservatives or the labor party back in the UK. India was merely a political entitiy that had been squeezed out of industry and any sense of identity or culture or institution. India's soul had always been in strangle hold of either middle-eastern (Islamic) or europeon coloniality in its imagination about itself. The genuine stupidity of the 1920's fraudulent polity, had further bastardised that notion. By 1930s, Britain saw indian people mainly under two major groups Indian National Congress and Muslim League. Muslim League sought to represent only the Indian Muslims and Indian National Congress claimed to represent everybody but was large ly looked at as a Hindu Party.

Whether India is a nation or not, has been the subject-matter of controversy between the Anglo-Indian and the non-muslim politicians ever since the Indian National Congress was founded. Anglo-indian politicians, who had founded INC (Indian National Congress) were never tired of proclaiming that India was not a nation. Even Dr. Tagore, the national poet of Bengal, agrees with them.

Dr. Ambedkar discusses the merits and pitfalls of both Non-Muslim and Muslim sides of arguments against and for Partition respectively, in his book "Pakistan or Partition of India". The Muslim's side of the argument is very simple and clear. Three Yes or No introspective questions, and a "Yes" to any of them means Muslims are a Nation and that makes a case for Pakistan.

>*Are Muslims an exclusive group? - Yes.*
>*Do Muslims have consciousness of a kind?" - Yes.*
>*Does Muslims have a longing to belong to ones own group, rather than any non-muslim group?" - An emphatic Yes! it is called an Ummah.*

The other side which is mostly Gandhi and his brown nosers, are vague and academically lacking. The argument, however flimsy, can broadly be put in the following points

1. Hindus and Muslims of India belong to the same race.
2. Both speak the same langauge and have same traditions (in their regions)
Hence the same Nation

Admist this is where i seek to search for my home, My Nation.

## Substance and Salience

Ernest Renan's lecture details on what our misunderstood notionms of nations is.

When you confound the race to a nation:

>*The truth of the matter is that there are no pure races; making politics depend on ethnographic analysis is to have it repose on a chimera. The most noble countries ! England, France, and Italy ! are those in which blood is the most mixed. Is Germany in this respect an exception? Is it a purely germanic country? What an illusion! The entire south of the country had been Gallic. All of the area east of the Elbe is Slavic. Are the parts that claim to be genuinely pure really that? We touch here on a problem of the greatest significance to making ideas clear and preventing misunderstandings.*

and when you confound linguistic substance for nationality :

>*Languages ask to be united, they do not force it. The United States and England, like Spanish America and Spain, speak the same language but do not constitute a single nation. By contrast, Switzerland, so well-made because created by the consent of its different parts, contains three or four languages.The desire of Switzerland to be united despite its linguistic variety is a much more important fact than similarity often achieved by humiliation.*

In Conclusion; nationality could be understood in renan's own words as :

>*A nation is a soul, a spiritual principle. Two things which, properly speaking, are really one and the same constitute this soul, this spiritual principle. One is the past, the other is the present. One is the possession in common of a rich legacy of memories; the other is present consent, the desire to live together, the desire to continue to invest in the heritage that we have jointly received.*

*Messieurs, man does not improvise. The nation, like the individual, is the outcome of a long past of efforts, sacrifices, and devotions!*

A Nation needs to have two very important ideas _*Substance*_ and _*Saliance*_ clearly outlined. That will let us comprehend the memories we possess and manufacture the desire within us to continue to invest in this heritage.

>**_Substance is what unites us_**

Substance is something that united all the Greek city states when Xerxes (Persian) attacked the Sparta, although each of these city states had considerable autonomy.

>**_Salience is what makes us different from others_**

For example : Deobandi and Bareilvi schools of islamic thoughts issue fatawas against each other all day long, but they are united in opposing Uniform Civil Code. Hindus on the other hand are like headless chicken. This cannot simply be put away with *there is no unity* statement. It is much more deeper insecurity of identity. *Being Secular* is not an identity. It is as tasteless and meaningless as *Being Human*.

## Conclusion

In this book i seek to understand, what my nation is? what is it not? what its philosophical underpinnings are? what should not be understood as substance? Where does that leave us? By us, i mean Hindus, as a social group. From Benedict's definition A Nation is simply an imagined identity, if so Indian Muslims should answer an emphatic "No" to the 3 questions that Ambedkar puts before them. Sadly, That is not happening.

Lets try to go back in time and inspect what that spiritual principle, that Renan points to, is for Pakistan. What is it for the rest of us in the subcontinent?

## Other Definitions of Nation

Otto Bauer, Austrian socialist, defines a nation as

>*The totality of people who are united by a common fate so that they possess a common (national) character. The common fate is primarily a common history; the common national character involves almost necessarily a uniformity of language.*

Stalin defines Nation and Nationality as given below.

>*Nation is a historically evolved, stable community of language, territory, economic life, and psychological makeup manifested in a community of culture. Nationality is not a racial or tribal phenomenon. It has five essential features: there must be a stable, continuing community, a common language, a distinct territory, economic cohesion, and a collective character. It assumes positive political form as a nation under definite historical conditions, belonging to a specific epoch, that of the rise of capitalism and the struggles of the rising bourgeosie under feudalism.*

Will Kymlicka, a Canadian political philosopher best known for his work on multiculturalism and animal ethics, defines nation in terms of a culture:

>*'Nation' means a historical community, more or less, institutionally complete, occupying. A given territory or homeland, sharing a distinct language and culture*

## Bibilography

1. Benedict Anderson, Imagined Communities: Reflection on the Origin and Spread of Nationalism, - https://is.muni.cz/el/1423/jaro2016/SOC757/um/61816961/Benedict_Anderson_Imagined_Communities.pdf

2. Muhammad Ali Jinnah - https://bepf.punjab.gov.pk/independence_through_ages

3. Sir Syed Ahmed Khan (1817–1898), Speech in March 1888, Quoted by Dilip Hiro, "The Longest August: The Unflinching Rivalry Between India and Pakistan" https://yaleglobal.yale.edu/longest-august-unflinching-rivalry-between-india-and-pakistan

4. Ernest Renan, "What is a Nation?" p6 http://ucparis.fr/files/9313/6549/9943/What_is_a_Nation.pdf


<!--chapter:end:01-intro.Rmd-->

# Literature

Here is a review of existing methods.

<!--chapter:end:02-literature.Rmd-->

# Methods

We describe our methods in this chapter.

Math can be added in body using usual syntax like this 

## math example

$p$ is unknown but expected to be around 1/3. Standard error will be approximated

$$
SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
$$

You can also use math in footnotes like this^[where we mention $p = \frac{a}{b}$].

We will approximate standard error to 0.027[^longnote]

[^longnote]: $p$ is unknown but expected to be around 1/3. Standard error will be approximated

    $$
    SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
    $$

<!--chapter:end:03-method.Rmd-->

# Applications

Some _significant_ applications are demonstrated in this chapter.

## Example one

## Example two

<!--chapter:end:04-application.Rmd-->

# Final Words

We have finished a nice book.

<!--chapter:end:05-summary.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:06-references.Rmd-->

